module.exports = {
  mainnet: {
    netId: 'mainnet',
    rpcURL: 'https://api.trongrid.io',
    smartRouter: 'TFVisXFaijZfeyeSjCEVkHfex7HGdTxzF9',
    old3pool: 'TKcEU8ekq2ZoFzLSGFYCUY6aocJBX9X31b',
    oldusdcpool: 'TQx6CdLHqjwVmJ45ecRzodKfVumAsdoRXH',
    routerV2: 'TKzxdSv2FZKQrEqkKVgp5DcwEXBEKMg2Ax',
    routerV1: 'TXk8rQSAvPvBBNtqSoY6nCfsXWCSSpTVQF',
    routerV3: 'TQAvWQpT9H916GckwWDJNhYZvQMkuRL7PN',
    v2Factory: 'TKWJdrQkqHisa1X8HUdHEfREvTzw4pMAaY',
    v3Factory: 'TThJt8zaJzJMhCEScH7zWKnp5buVZqys9x',
    usdtToken: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t',
    usdjToken: 'TMwFHYXLJaRUPeW6421aqXL4ZEzPRFGkGT',
    tusdToken: 'TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4',
    usdcToken: 'TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8',
    psmUsddToken: 'TPYmHEhy5n8TCEfYGqW2rPxsghSfzghPDn',
    wtrxToken: 'TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR',
    usddToken: 'TPYmHEhy5n8TCEfYGqW2rPxsghSfzghPDn',
    usdd2pool: 'TNTfaTpkdd4AQDeqr8SGG7tgdkdjdhbP5c',
    usdtpsmpool: {
      psm: 'TM9gWuCdFGNMiT1qTq1bgw4tNhJbsESfjA',
      gemJoin: 'TMn5WeW8a8KH9o8rBQux4RCgckD2SuMZmS',
    },
    usdcpsmpool: {
      psm: 'TUcj1rpMgJCcFZULyq7uLbkmfh9xMnYTmA',
      gemJoin: 'TRGTuMiDYAbztetdndYyMzYvtaRmucjz5q',
    },
    tusdpsmpool: {
      psm: 'TY2op6AKcEkFhv8hxNJj3FBUfjManxYLSe',
      gemJoin: 'TPxcmB9dQC3LHswCNEc4rJs1HFGb8McYjT',
    },
    usdjpsmpool: {
      psm: 'TVS3rVDUSd3ySeXV5moRH2J2t5B9reJfLR',
      gemJoin: 'TKAovR61zwp1t9Rg1UE4UY5mXt7QTJdDXg',
    },
    tusdusdt2pool: 'TS8d3ZrSxiGZkqhJqMzFKHEC1pjaowFMBJ',
    usdc2pooltusdusdt: 'TE7SB1v9vRbYRe5aJMWQWp9yfE2k9hnn3s',
    usdd2pooltusdusdt: 'TLssvTsY4YZeDPwemQvUzLdoqhFCbVxDGo',
    usdj2pooltusdusdt: 'TKBqNLyGJRQbpuMhaT49qG7adcxxmFaVxd',
  },
  nile: {
    netId: 'nile',
    rpcURL: 'https://api.nileex.io',
    // smartRouter: 'TNR6sqRYBmKQFHK88uKsvxGm167AopiQqV',
    // smartRouter: 'TC3dPwf5t7fWDrCR4r2q9b1K4YDoULETzn',
    smartRouter: 'TENHSdAEm2odXopAFu1ZwntrXpaGtoS1Tq',
    old3pool: 'TW6tDjosBGXpjnRMQnHAhPuqTubGs93B9E',
    oldusdcpool: 'TJ9d9GXCsF7cmnHDLrtT4qo6kNbVK7Qebr',
    routerV3: 'TFkswj6rUfK3cQtFGzungCkNXxD2UCpEVD',
    routerV2: 'TMn1qrmYUMSTXo9babrJLzepKZoPC7M6Sy',
    routerV1: 'TXFouUxm4Qs3c1VxfQtCo4xMxbpwE3aWDM',
    v2Factory : 'THomLGMLhAjMecQf9FQjbZ8a1RtwsZLrGE',
    v3Factory : 'TLJWAScHZ4Qmk1axyKMzrnoYuu2pSLer1F',
    usdtToken: 'TXYZopYRdj2D9XRtbG411XZZ3kM5VkAeBf',
    usdjToken: 'TLBaRhANQoJFTqre9Nf1mjuwNWjCJeYqUL',
    tusdToken: 'TRz7J6dD2QWxBoumfYt4b3FaiRG23pXfop',
    usdcToken: 'TWMCMCoJPqCGw5RR7eChF2HoY3a9B8eYA3',
    ethToken: 'TQz9i4JygMCzizdVu8NE4BdqesrsHv1L93',
    sunoldToken: 'TWrZRHY9aKQZcyjpovdH6qeCEyYZrRQDZt',
    sunToken : 'TDqjTkZ63yHB19w2n7vPm2qAkLHwn9fKKk',
    psmUsddToken: 'TWvPn9LWmNd1DMtt52yKHhNJazi7sDfcUq',
    wtrxToken: 'TYsbWxNnyTgsZaTFaue9hqpxkU3Fkco94a',
    usddToken: 'TGjgvdTWWrybVLaVeFqSyVqJQWjxqRYbaK',
    usdd2pool: 'TH6ZjnptwVgtaTFhCJfkv3B9WVjkGW9mcr',
    btctoken : 'TG9XJ75ZWcUw69W8xViEJZQ365fRupGkFP',
    usdtpsmpool: {
      psm: 'TF12vhGuWttHNfxsrn6XueMLvxGLVCyN12',
      gemJoin: 'TVymSS688hC4pB4pkNsVZuy6ESwfkZD5wV',
    },
    usdcpsmpool: {
      psm: 'TFDUZ6FAtXptkY3dKHk2oRarCckyDYRkEL',
      gemJoin: 'TXcDefjzD3GKEVs2Fg3aF8uiSeLe2baUF6',
    },
    tusdpsmpool: {
      psm: 'TBJ1sR6RGj5675ZuHWGrG18tMxjo7cifJB',
      gemJoin: 'TCajxTTRLHfeBP1cpmvAxTmHRtuKswQkqN',
    },
    usdjpsmpool: {
      psm: 'TAkD9tpd6MWVM3MQjrfDRGCXwiRMUGzzYh',
      gemJoin: 'TYoPrfWjkzhTSqcGkVWYcV1CEa3xWBj5ej',
    },
    tusdusdt2pool: 'TJ1iMSq3o7zWRQkqyytRv7BYpNBKVYy1jk',
    usdc2pooltusdusdt: 'TJicAdxwkexTfybwVFjZ8TwUjMf5pTkhUP',
    usdd2pooltusdusdt: 'TXLCb7vwLB9HzcWB5izoggirQsqQAtJwfU',
    usdj2pooltusdusdt: 'TV7ybcx4wxo4L6R8EsRcV6AZD7sCRkmADg',
  },
};
